#!/bin/sh

set -e

if test $1 != "upgrade"; then
    update-alternatives --remove yacc /usr/bin/btyacc
    update-alternatives --remove yaccman /usr/share/man/man1/btyacc.1.gz
fi

#DEBHELPER#

exit 0


